In [1]:
!sudo apt-get -y update
!sudo apt-get -y install python3-pip
!sudo apt-get -y install python-is-python3
!pip install -U pip
!pip install tensorflow==2.17.0
!pip install -U onnx==1.16.1
!pip install onnx_graphsurgeon --index-url https://pypi.ngc.nvidia.com
!pip install -U onnxruntime==1.18.1
!pip install -U onnxsim==0.4.33
!pip install -U simple_onnx_processing_tools
!pip install -U onnx2tf
!pip install -U protobuf==3.20.3
!pip install -U h5py==3.11.0
!pip install -U psutil==5.9.5
!pip install -U ml_dtypes==0.3.2
!pip install flatbuffers>=23.5.26

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Hit:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease [24.3 kB]
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,647 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2,904 kB]
Get:13 https://r2u.stat.illinois.edu/ubuntu jammy/main all Package

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 70.1 MB/s eta 0:00:00
  Attempting uninstall: h5py
    Found existing installation: h5py 3.12.1
    Uninstalling h5py-3.12.1:
      Successfully uninstalled h5py-3.12.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-text 2.18.1 requires tensorflow<2.19,>=2.18.0, but you have tensorflow 2.17.0 which is incompatible.
tf-keras 2.18.0 requires tensorflow<2.19,>=2.18, but you have tensorflow 2.17.0 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 49.3 MB/s eta 0:00:00
  Attempting uninstall: ml_dtypes
    Found existing installation: ml-dtypes 0.4.1
    Uninstalling ml-dtypes-0.4.1:
      Successfully uninstalled ml-dtypes-0.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the fo

In [1]:
!wget https://github.com/PINTO0309/onnx2tf/releases/download/0.0.2/resnet18-v1-7.onnx onnx2tf -i resnet18-v1-7.onnx

Streaming output truncated to the last 5000 lines.
>~�)>(%>9>���=�E\>��>���>��>)���#9ƽ����N�	�!=I0=ֻ�=�Z=�β=��=�[�%A=�*w=<�"��^;L�$>�N���>'��=���<^�<u�>�<~o�=���>f;�>��>�: Invalid host name
��>SA�>/,>���>m�v>=�: Invalid host name
<�ļ$�	��4����2=�^��X%i=��>��!>nq�=��=[��=��[=�T�<hfS=�j�/=8�>#`!>fp>�^�>�^W>�~�>�M�>\�>���>)o�>y�>�/�>w�>��|>���>��>Uc�>���>pG�>�#�>{��>&�=: Invalid host name
�<�U���Q��5�G^�: Invalid host name
2>Nu>!�9=%��=\����C��C����ı�.����a��j������]�������KH��;�֬U<�v=Bغ\(�=8�Q>�1c>t�>�"ʾ����Ӿ�%���IZ�:���Y�mz�����-�@={k�<�?�������	��P�����3�N+q�R�����q�Mܮ�Rt��!B��Դ��Q��L<��s|��aS8>: Invalid host name
resnet18-v1-7.onnx: Invalid URL http://%��H��9���K$: Invalid host name
resnet18-v1-7.onnx: Invalid URL http://?m��i��$l�^�Z��dB��F�=a>�ǥ=M��dݽb��H���U���O��H��l�O�ɽ��ü�������S>=�>ĥ�=SDY�����2H��伽�=3�ѽv,��|n$=��?�T,e��/k��8���༼�$<�:=�7���@����<�Þ>T_`>y=�>�8Q>F�=��>�>=K�>e��>��Lw��p酾�i9�R�0���v����V����

In [7]:
!onnx2tf -i /content/drive/MyDrive/trained_models/mobile_docunet.onnx


Model optimizing started ============================================================
Simplifying...
Finish! Here is the difference:
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃                   ┃ Original Model ┃ Simplified Model ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Add               │ 10             │ 10               │
│ Concat            │ 4              │ 1                │
│ Constant          │ 156            │ 146              │
│ Conv              │ 72             │ 72               │
│ GlobalAveragePool │ 9              │ 9                │
│ HardSigmoid       │ 8              │ 8                │
│ HardSwish         │ 20             │ 20               │
│ Mul               │ 8              │ 8                │
│ Relu              │ 27             │ 27               │
│ Resize            │ 3              │ 3                │
│ Shape             │ 3              │ 0                │
│ Slice             │ 3              │ 0              

In [9]:
import tensorflow as tf

# Load the TensorFlow SavedModel
saved_model_dir = 'saved_model'
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)

# Convert the model to TFLite format
tflite_model = converter.convert()

# Save the TFLite model to a file
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)

In [10]:
import numpy as np
import tensorflow as tf

# Load the TFLite model
interpreter = tf.lite.Interpreter(model_path='model.tflite')
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Prepare input data
input_data = np.array(np.random.random_sample(input_details[0]['shape']), dtype=np.float32)

# Set the input tensor
interpreter.set_tensor(input_details[0]['index'], input_data)

# Run inference
interpreter.invoke()

# Get the output tensor
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

[[[[0.1728946  0.38779795]
   [0.1728946  0.38779795]
   [0.1728946  0.38779795]
   ...
   [0.31461155 0.46184078]
   [0.31461155 0.46184078]
   [0.31461155 0.46184078]]

  [[0.1728946  0.38779795]
   [0.1728946  0.38779795]
   [0.1728946  0.38779795]
   ...
   [0.31461155 0.46184078]
   [0.31461155 0.46184078]
   [0.31461155 0.46184078]]

  [[0.1728946  0.38779795]
   [0.1728946  0.38779795]
   [0.1728946  0.38779795]
   ...
   [0.31461155 0.46184078]
   [0.31461155 0.46184078]
   [0.31461155 0.46184078]]

  ...

  [[0.15301609 0.27313775]
   [0.15301609 0.27313775]
   [0.15301609 0.27313775]
   ...
   [0.26108667 0.188074  ]
   [0.26108667 0.188074  ]
   [0.26108667 0.188074  ]]

  [[0.15301609 0.27313775]
   [0.15301609 0.27313775]
   [0.15301609 0.27313775]
   ...
   [0.26108667 0.188074  ]
   [0.26108667 0.188074  ]
   [0.26108667 0.188074  ]]

  [[0.15301609 0.27313775]
   [0.15301609 0.27313775]
   [0.15301609 0.27313775]
   ...
   [0.26108667 0.188074  ]
   [0.26108667 0.188074

In [11]:
import tensorflow as tf

# Load the TFLite model
interpreter = tf.lite.Interpreter(model_path="/content/drive/MyDrive/trained_models/mobile_docunet_float16.tflite")
interpreter.allocate_tensors()

# Get input and output details
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print("Input Shape:", input_details[0]['shape'])
print("Input Data Type:", input_details[0]['dtype'])
print("Output Shape:", output_details[0]['shape'])
print("Output Data Type:", output_details[0]['dtype'])

Input Shape: [  1 256 256   3]
Input Data Type: <class 'numpy.float32'>
Output Shape: [  1 256 256   2]
Output Data Type: <class 'numpy.float32'>


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import tensorflow as tf

# Load the TensorFlow SavedModel
saved_model_dir = 'saved_model'
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)

# Convert the model to TFLite format
tflite_model = converter.convert()

# Save the TFLite model to a file
with open('model.tflite', 'wb') as f:
f.write(tflite_model)